# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('lugar', models.CharField(max_length=200)),
                ('fechaRealizacion', models.DateField(verbose_name='fecha realizacion')),
                ('hora', models.TimeField()),
                ('descripcion', models.TextField(max_length=800)),
                ('imagen', models.CharField(max_length=100)),
                ('fechaPublicacion', models.DateField(verbose_name='fecha publicacion')),
                ('puntuacion', models.IntegerField(default=0)),
                ('visitas', models.IntegerField(default=0)),
                ('autorizado', models.SmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['-fechaRealizacion'],
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
            },
        ),
        migrations.CreateModel(
            name='Capsulas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPublicacion', models.DateField(verbose_name='fecha publicacion')),
                ('texto', models.TextField(max_length=225)),
                ('autorizado', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(max_length=200)),
                ('fechaComentario', models.DateField(verbose_name='fecha comentario')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArtista', models.CharField(max_length=100)),
                ('nombreReal', models.CharField(max_length=65)),
                ('imagen', models.CharField(max_length=100)),
                ('sexo', models.SmallIntegerField(default=0)),
                ('fechaNacimiento', models.DateField(auto_now=True, verbose_name='fecha nacimiento')),
                ('telefono', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254, verbose_name='Correo invalido')),
                ('descripcion', models.CharField(max_length=200)),
                ('fechaRegistro', models.DateField(auto_now=True, verbose_name='fecha registro')),
                ('visitas', models.IntegerField(default=0)),
                ('autorizado', models.SmallIntegerField(default=0)),
                ('categoria', models.ManyToManyField(to='home.Categoria')),
            ],
            options={
                'ordering': ['-fechaRegistro'],
                'verbose_name': 'pefil',
                'verbose_name_plural': 'perfiles',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRol', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=40)),
                ('ultimaConexion', models.DateField(verbose_name='ultima conexion')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Perfil')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Rol')),
            ],
        ),
        migrations.AddField(
            model_name='capsulas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Usuarios'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='categoria',
            field=models.ManyToManyField(to='home.Categoria'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='perfil',
            field=models.ManyToManyField(to='home.Perfil'),
        ),
    ]
