# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 23:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='rol',
        ),
        migrations.AlterModelManagers(
            name='capsulas',
            managers=[
                ('public', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fechaPublicacion',
            field=models.DateField(verbose_name='Fecha de publicacion'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fechaRealizacion',
            field=models.DateField(verbose_name='Fecha a realizar'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='hora',
            field=models.TimeField(verbose_name='Hora de Realizacion'),
        ),
        migrations.AlterField(
            model_name='capsulas',
            name='fechaPublicacion',
            field=models.DateField(verbose_name='Fecha de publicacion'),
        ),
        migrations.AlterField(
            model_name='capsulas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='fechaComentario',
            field=models.DateField(verbose_name='Fecha del comentario'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fechaNacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fechaRegistro',
            field=models.DateField(verbose_name='Fecha de registro'),
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
