# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArtista', models.CharField(max_length=100)),
                ('nombreReal', models.CharField(max_length=65)),
                ('imagen', models.CharField(max_length=100)),
                ('fechaNacimimiento', models.DateTimeField(verbose_name='Fecha de Nacimiento')),
                ('telefono', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254, verbose_name='Correo invalido')),
                ('descripcion', models.CharField(max_length=200)),
                ('fechaRegistro', models.DateTimeField(verbose_name='Fecha de Registro')),
                ('visitas', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
