# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20161020_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='fechaNacimimiento',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='fechaRegistro',
        ),
    ]
