# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20161020_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='autorizado',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sexo',
            field=models.SmallIntegerField(default=0),
        ),
    ]
