# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20161020_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='autorizado',
            field=models.SmallIntegerField(default=0),
        ),
    ]
