# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20161020_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(max_length=200)),
                ('fechaComentario', models.DateField(verbose_name='fecha comentario')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Actividad')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='categoria',
            field=models.ManyToManyField(to='polls.Categoria'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='categoria',
            field=models.ManyToManyField(to='polls.Categoria'),
        ),
    ]
