# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20161020_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capsulas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPublicacion', models.DateField(verbose_name='fecha publicacion')),
                ('texto', models.TextField(max_length=225)),
                ('autorizado', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRol', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=40)),
                ('ultimaConexion', models.DateField(verbose_name='ultima conexion')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Perfil')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Rol')),
            ],
        ),
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['-fechaRealizacion'], 'verbose_name': 'actividad', 'verbose_name_plural': 'actividades'},
        ),
        migrations.AddField(
            model_name='actividad',
            name='perfil',
            field=models.ManyToManyField(to='polls.Perfil'),
        ),
        migrations.AddField(
            model_name='capsulas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Usuarios'),
        ),
    ]
