# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20161020_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='fechaPublicacion',
            field=models.DateField(verbose_name='Fecha de publicacion'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fechaRealizacion',
            field=models.DateField(verbose_name='Fecha a realizar'),
        ),
        migrations.AlterField(
            model_name='capsulas',
            name='fechaPublicacion',
            field=models.DateField(verbose_name='Fecha de publicacion'),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='fechaComentario',
            field=models.DateField(verbose_name='Fecha del comentario'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fechaNacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fechaRegistro',
            field=models.DateField(verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='ultimaConexion',
            field=models.DateField(verbose_name='Ultia conexion'),
        ),
    ]
